name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet publish Studentregistration -c Release -o publish   

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact files
          path: publish

  deploy:
    needs: build
    uses: ./.github/workflows/Deploy.yml
    with:
      name: files
