name: Matrix

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment: dev
            message: "Hello"
          - environment: qa
            message: "All the next"
          - environment: prod
            message: "Bye"

    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"
