name:  Matrix

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Print environment
        run: echo "Running for ${{ matrix.environment }}"
