name: Matrix Condition

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Print Hello  for dev
        if: matrix.environment == 'dev'
        run: echo "Hello"

      - name: Print All for qa
        if: matrix.environment == 'qa'
        run: echo "All the next"

      - name: Print Bye  prod
        if: matrix.environment == 'prod'
        run: echo "Bye"
